version: '2'
services:
    jhipstersampleapplication-app:
        image: jhipstersampleapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=jhipstersampleapplication-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    jhipstersampleapplication-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: jhipstersampleapplication-cassandra
    jhipstersampleapplication-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=jhipstersampleapplication-cassandra
    jhipstersampleapplication-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhipstersampleapplication-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
